export default {
	friends(){
		let friendarr = [
			{
				id:1,
				imgurl:'four.png',
				tip:2,
				name:'大海',
				time:new Date(),
				news:'文件（Object）上传至存储空间（Bucket）后，OSS会自动生成文件URL，您可以直接通过文件URL',
			},
			{
				id:2,
				imgurl:'one.png',
				tip:2,
				name:'山川',
				time:new Date(),
				news:'文件（Object）上传至存储空间（Bucket）后，OSS会自动生成文件URL，您可以直接通过文件URL',
			},
			{
				id:4,
				imgurl:'four.png',
				tip:1,
				name:'河流',
				time:new Date(),
				news:'文件（Object）上传至存储空间（Bucket）后',
			},
			{
				id:3,
				imgurl:'two.png',
				tip:0,
				name:'天空',
				time:new Date(),
				news:'OSS会自动生成文件URL，您可以直接通过文件URL',
			},
			{
				id:5,
				imgurl:'three.png',
				tip:99,
				name:'太空',
				time:new Date(),
				news:'海大海大海大海大海大海大海大海大海大海大海大海大海大海大海大海',
			},
			{
				id:6,
				imgurl:'four.png',
				tip:33,
				name:'大海',
				time:new Date(),
				news:'（即Bucket外网访问域名）访问该文件。若您希望通过自定义域名（自有域名）访问这些文件，需要将自定义域名绑定至文件所在的Bucket。',
			},
			{
				id:7,
				imgurl:'four.png',
				tip:1,
				name:'大海',
				time:new Date(),
				news:'文件（Object）上传至存储空间（Bucket）后，OSS会自动生成文件URL，您可以直接通过文件URL（即Bucket外网访问域名）访问该文件。若您希望通过自定义域名（自有域名）访问这些文件，需要将自定义域名绑定至文件所在的Bucket。',
			},
			{
				id:8,
				imgurl:'four.png',
				tip:2,
				name:'大海',
				time:new Date(),
				news:'文件（Object）上传至存储空间（Bucket）后，OSS会自动生成文件URL，您可以直接通过文件URL',
			},
			{
				id:9,
				imgurl:'one.png',
				tip:2,
				name:'山川',
				time:new Date(),
				news:'文件（Object）上传至存储空间（Bucket）后，OSS会自动生成文件URL，您可以直接通过文件URL',
			},
			{
				id:10,
				imgurl:'four.png',
				tip:1,
				name:'河流',
				time:new Date(),
				news:'文件（Object）上传至存储空间（Bucket）后',
			},
			{
				id:11,
				imgurl:'two.png',
				tip:0,
				name:'天空',
				time:new Date(),
				news:'OSS会自动生成文件URL，您可以直接通过文件URL',
			},
			{
				id:12,
				imgurl:'three.png',
				tip:99,
				name:'太空',
				time:new Date(),
				news:'海大海大海大海大海大海大海大海大海大海大海大海大海大海大海大海',
			},
			{
				id:13,
				imgurl:'four.png',
				tip:33,
				name:'大海',
				time:new Date(),
				news:'（即Bucket外网访问域名）访问该文件。若您希望通过自定义域名（自有域名）访问这些文件，需要将自定义域名绑定至文件所在的Bucket。',
			},
			{
				id:14,
				imgurl:'four.png',
				tip:1,
				name:'大海',
				time:new Date(),
				news:'文件（Object）上传至存储空间（Bucket）后，OSS会自动生成文件URL，您可以直接通过文件URL（即Bucket外网访问域名）访问该文件。若您希望通过自定义域名（自有域名）访问这些文件，需要将自定义域名绑定至文件所在的Bucket。',
			},
		];
		return friendarr
	}
}